### ISSUE TITLE
The current `SESSION_EXPIRED` mechanism is too rigid

### ISSUE THREAD

**Issue by zsoltboldizsar** [halcyonmobile/retrofit-oauth2-helper#67]
The current `SESSION_EXPIRED` mechanism can only be triggered if a `retrofit2.HttpException` is thrown, therefore when using this library in combination with [`Retrofit-Error-Parsing`](https://github.com/halcyonmobile/retrofit-error-wrapping), which throws its own custom exception ([NetworkException](https://github.com/halcyonmobile/retrofit-error-wrapping/blob/master/error-parsing/src/main/java/com/halcyonmobile/errorparsing2/NetworkException.kt)), the `SESSION_EXPIRED` mechanism simply gets bypassed, resulting in the consumer not being informed about the incident (instead of being logged out, users would remain logged in and being shown errors for any attempt of accessing remote resources).

**Comment by fknives** [comment]
Hey,
Thanks for the report, this is indeed a design flaw and should have been reported and fixed a while back :+1:
Even though it can be worked around with the current `IsSessionExpiredException`  and `ErrorResponseToExceptionConverter.Factory` it makes sense to adjust this library, I completely agree.

However I think since it can be worked around it would be good to keep backward compatibility so existing workarounds don't break, they just become deprecated.
I am going to review the PR now, and see if it can be kept as backward compatible if you are agreeing with my reasoning.

**Comment by zsoltboldizsar** [comment]
Yeah, I've had this on my todo list as well for a good while now, didn't have time to file a PR for it until now. 🙂 

I wasn't aware of any workaround, but I'm pretty sure it'll break it as I changed the method signatures in `IsSessionExpiredException`. Anyway, thanks for taking the time to review it 👍🏼
